version: "3.7"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.3"
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
#        labels:
#            - traefik.enable=true
#            - traefik.http.routers.elastic.rule=Host(`elastic.docker.localhost`)
#            - traefik.http.services.elastic.loadbalancer.server.port=9200
        volumes:
            - .data:/usr/share/elasticsearch/data
        networks:
            - default
            - traefik

    kibana:
        image: "docker.elastic.co/kibana/kibana:8.5.3"
        labels:
            - traefik.enable=true
            - traefik.http.routers.kibana.rule=Host(`elk.docker.localhost`)
            - traefik.http.services.kibana.loadbalancer.server.port=5601
        networks:
            - default
            - traefik

#    filebeat:
#        image: ehyiah/filebeat:1.0
#        volumes:
#            - ./var/log:/usr/share/var/symfony:ro
#            - ./var/caddy:/usr/share/var/caddy:ro
#            - /var/lib/docker:/var/lib/docker:ro
#            - /var/run/docker.sock:/var/run/docker.sock
#        networks:
#            - elk
#    SET project name to get a elastic tag to facilitate search
#        environment:
#            - PROJECT_NAME=my_project_name


networks:
    traefik:
        external: true
    default:
        name: elk
        driver: bridge
